version: "2"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
      POSTGRES_DB: albatros_product
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - "db"
    ports:
      - 9090:8080
  mockServer:
    image: mockserver/mockserver:5.14.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123 -queue "projects/dev/locations/asia-east1/queues/testproject"
    ports:
      - "${TASKS_PORT:-8123}:8123"
    environment:
      APP_ENGINE_EMULATOR_HOST: http://localhost:9391
      DEBUG: "true"
  pubsub:
    image: singularities/pubsub-emulator
    environment:
      - PUBSUB_PROJECT_ID=sample-test
      - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8681
    ports:
      - "8681:8681"